server:
  port: 8080

spring:
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

  management:
    endpoints:
      web:
        exposure:
          include: health,info,circuitbreakers,circuitbreakerevents
    endpoint:
      health:
        show-details: always
    info:
      title: User Service API
      description: API для управления пользователями
      version: 1.0.0
      contact:
        name: Vadim
        email: vadim@example.com