server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false  # Сам себя не регистрирует
    fetch-registry: false
  server:
    enable-self-preservation: false  # Для dev-окружения